import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

/// Git hook script template for pre-commit.
const preCommitHookTemplate = '''
#!/bin/sh
# Alfredo pre-commit hook
# Auto-generated by `alfredo hooks install`

set -e

# Run format and analyze checks
if [ -f "scripts/dart-sandbox.sh" ]; then
  ./scripts/dart-sandbox.sh format --set-exit-if-changed .
  ./scripts/dart-sandbox.sh analyze --fatal-infos --fatal-warnings
elif command -v dart >/dev/null 2>&1; then
  dart format --set-exit-if-changed .
  dart analyze --fatal-infos --fatal-warnings
fi
''';

/// Manages Git hooks for an Alfredo project.
class HooksCommand extends Command<int> {
  /// Creates the hooks command.
  HooksCommand({required Logger logger}) {
    addSubcommand(_HooksInstallCommand(logger: logger));
    addSubcommand(_HooksUninstallCommand(logger: logger));
  }

  @override
  String get description => 'Manage Git hooks for code quality and workflows.';

  @override
  String get name => 'hooks';
}

class _HooksInstallCommand extends Command<int> {
  _HooksInstallCommand({required this.logger}) {
    argParser.addFlag(
      'force',
      abbr: 'f',
      help: 'Overwrite existing hooks if present.',
    );
  }

  final Logger logger;

  @override
  String get description => 'Install Git hooks in the current repository.';

  @override
  String get name => 'install';

  @override
  Future<int> run() async {
    final gitDir = Directory('.git');
    if (!gitDir.existsSync()) {
      logger.err('Not a git repository. Cannot install hooks.');
      return ExitCode.usage.code;
    }

    final hooksDir = Directory(p.join(gitDir.path, 'hooks'));
    if (!hooksDir.existsSync()) {
      await hooksDir.create(recursive: true);
    }

    final preCommitFile = File(p.join(hooksDir.path, 'pre-commit'));
    final force = argResults!['force'] as bool;

    if (preCommitFile.existsSync() && !force) {
      logger.err('Hook pre-commit already exists. Use --force to overwrite.');
      return ExitCode.config.code;
    }

    await preCommitFile.writeAsString(preCommitHookTemplate);

    // Make executable on Unix-like systems
    if (!Platform.isWindows) {
      await Process.run('chmod', ['+x', preCommitFile.path]);
    }

    logger.success('Installed Git hooks successfully.');
    return ExitCode.success.code;
  }
}

class _HooksUninstallCommand extends Command<int> {
  _HooksUninstallCommand({required this.logger});

  final Logger logger;

  @override
  String get description => 'Uninstall Git hooks from the current repository.';

  @override
  String get name => 'uninstall';

  @override
  Future<int> run() async {
    final hooksDir = Directory(p.join('.git', 'hooks'));
    final preCommitFile = File(p.join(hooksDir.path, 'pre-commit'));

    if (preCommitFile.existsSync()) {
      await preCommitFile.delete();
      logger.success('Uninstalled Git hooks successfully.');
    } else {
      logger.info('No hooks to uninstall.');
    }

    return ExitCode.success.code;
  }
}
