const $=s=>document.querySelector(s), state=$('#state'), answer=$('#answer'), meta=$('#meta');
const setState=(s,busy=false)=>{state.textContent=s;document.querySelectorAll('button').forEach(x=>x.disabled=busy)};
async function jsonFetch(url,options={}){const r=await fetch(url,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.error?.message||`Erro HTTP ${r.status}`);return data}
async function loadStatus(){try{const [health,ps]=await Promise.all([jsonFetch('/api/health'),jsonFetch('/api/providers')]);$('#health').textContent=`● ${health.status} · ${health.providers_available} disponíveis`;$('#providers').innerHTML=ps.map(p=>`<div class="provider"><strong>${p.available?'✓':'×'} ${p.name}</strong><small>${escapeHtml(p.diagnostic)}</small>${p.models.length?`<small>${p.models.map(escapeHtml).join(' · ')}</small>`:''}</div>`).join('')}catch(e){$('#health').textContent='× Offline';$('#providers').textContent=e.message}}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function escapeAttr(v=''){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll("'",'&#39;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
$('#provider').addEventListener('change',()=>{$('#model-wrap').hidden=!['auto','ollama'].includes($('#provider').value)});
$('#chat-form').addEventListener('submit',async e=>{e.preventDefault();setState('Pensando',true);answer.textContent='Processando…';meta.innerHTML='';try{const p=$('#provider').value,context=[...document.querySelectorAll('.note-select:checked')].map(x=>x.value);const d=await jsonFetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('#message').value,provider:p,model:p==='ollama'?$('#model').value:null,allow_fallback:$('#fallback').checked,context})});answer.textContent=d.answer||d.error?.message||'Sem resposta.';answer.className=d.error?'answer error':'answer';const tools=d.tools_used?.length?d.tools_used.map(t=>`<span class="tool-use">${t.ok?'✓':'×'} ${escapeHtml(t.name)} · ${t.duration_ms} ms</span>`).join(' '):'Nenhuma';meta.innerHTML=`<dt>Solicitado</dt><dd>${d.requested_provider}</dd><dt>Utilizado</dt><dd>${d.used_provider||'—'}${d.fallback_used?' (fallback)':''}</dd><dt>Modelo</dt><dd>${d.model||'—'}</dd><dt>Duração</dt><dd>${d.duration_ms} ms</dd><dt>Roteamento</dt><dd>${escapeHtml(d.routing_reason)}</dd><dt>Ferramentas</dt><dd>${tools}</dd><dt>Notas usadas</dt><dd>${d.notes_used.length?d.notes_used.map(escapeHtml).join(', '):'Nenhuma'}</dd>`;if(d.answer&&$('#speak-answer').checked){setState('Falando');await jsonFetch('/api/speak',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:d.answer})})}}catch(e){answer.textContent=e.message;answer.className='answer error'}finally{setState('Pronto')}});
let recorder,chunks=[];const talk=$('#talk');
async function startTalk(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setState('Transcrevendo',true);try{const blob=new Blob(chunks,{type:recorder.mimeType});const form=new FormData();form.append('audio',blob,'voice.webm');const d=await jsonFetch('/api/transcribe',{method:'POST',body:form});$('#message').value=d.text;setState('Pronto')}catch(e){answer.textContent=e.message;answer.className='answer error';setState('Erro')}};recorder.start();talk.classList.add('listening');talk.setAttribute('aria-pressed','true');setState('Ouvindo');talk.disabled=false}catch(e){answer.textContent='Não foi possível acessar o microfone. Verifique a permissão do navegador.';answer.className='answer error';setState('Erro')}}
function stopTalk(){if(recorder?.state==='recording'){recorder.stop();talk.classList.remove('listening');talk.setAttribute('aria-pressed','false')}}
talk.addEventListener('pointerdown',startTalk);talk.addEventListener('pointerup',stopTalk);talk.addEventListener('pointercancel',stopTalk);talk.addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();startTalk()}});talk.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter')stopTalk()});
$('#search-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await jsonFetch(`/api/memory/search?q=${encodeURIComponent($('#search').value)}`);$('#notes').innerHTML=d.results.length?d.results.map(n=>`<div class="note"><label class="check"><input class="note-select" type="checkbox" value="${escapeAttr(n.path)}"> Usar esta nota na próxima pergunta</label><strong>${escapeHtml(n.title)}</strong><small>${escapeHtml(n.path)}</small><p>${escapeHtml(n.excerpt)}</p></div>`).join(''):'Nenhuma nota encontrada.'}catch(e){$('#notes').textContent=e.message}});
$('#memory-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await jsonFetch('/api/memory/propose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:$('#memory-path').value,title:$('#memory-title').value,content:$('#memory-content').value})});$('#proposal').innerHTML=`<p><strong>${escapeHtml(d.title)}</strong><br><small>${escapeHtml(d.path)}</small></p><pre>${escapeHtml(d.content)}</pre><button id="approve">Aprovar e gravar</button>`;$('#approve').onclick=async()=>{try{const r=await jsonFetch('/api/memory/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proposal_id:d.id})});$('#proposal').textContent=`Gravado com aprovação: ${r.path}`}catch(e){$('#proposal').textContent=e.message}}}catch(e){$('#proposal').textContent=e.message}});
loadStatus();
